let suggestion =[
    "How to make a protfolio",
    "Claverprogrammer",
    "Reactjs",
    "Sonny Sanga",
    "React Native",
    "Faysal Mrihda",
    "Faysal Mrihda",
    "Faysal Mrihda",
    "Faysal Mrihda",
    "Faysal Mrihda",
    "Faysal Mrihda",
    "Faysal Mrihda",
    "Faysal Mrihda",
    "Faysal Mrihda",
    "Faysal Mrihda",
    "Faysal Mrihda",
    "Faysal Mrihda",
    "Faysal Mrihda",
    "Faysal Mrihda",
    "Faysal Mrihda",
    "Faysal Mrihda",
    "Faysal Mrihda",
    "Faysal Mrihda",
    "Faysal Mrihda",
    "Faysal Mrihda",
    "Faysal Mrihda",
    "Faysal Mrihda",
    "Faysal Mrihda",
    "Faysal Mrihda",
    "Faysal Mrihda",
    "Faysal Mrihda",
    "Faysal Mrihda",
    "Faysal Mrihda",
    "Faysal Mrihda",
    "Faysal Mrihda",
    "Faysal Mrihda",
    "Faysal Mrihda",
    "Faysal Mrihda",
    "Faysal Mrihda",
    "Faysal Mrihda",
    "Faysal Mrihda",
    "Faysal Mrihda",
    "lorem",
    "3d animaion",
    "Python",
    "Swift",
    "Java",
]